### ISSUE TITLE
Swinger / Waltzify?

### ISSUE THREAD

**Issue by wolftune** [algorithmic-music-exploration/amen#107]
Is there a way to use https://github.com/echonest/remix-examples/tree/master/waltzify and https://github.com/echonest/remix-examples/tree/master/swinger with amen?

Or do they need some rewriting?

**Comment by tkell** [comment]
Hello!

You could hack them now, but it is not great:  Amen has no concept of 8th notes, so you'd need to split Beats in two by hand, and then do some tacky time-stretching.

**Comment by wolftune** [comment]
@tkell thanks, is there already an issue for building the necessary backend for Amen?

**Comment by tkell** [comment]
I can write them up, sure - I am not going to be doing any deep work on this for a while though, for the record.

**Comment by tkell** [comment]
Moved to #108 and #109, closing this one.
