### ISSUE TITLE
Is amen dead?

### ISSUE THREAD

**Issue by tomswisher** [algorithmic-music-exploration/amen#112]
I would donate at the top tier to a Patreon to keep Amen going, or the 2018 equivalent. Pyechonest Remix catalyzed my push into professional frontend & dataviz development.

**Comment by bmcfee** [comment]
I wouldn't say that it's dead, but it's also not a high priority item for us (the devs) right now.

There are a number of things that need doing within amen, and many of them are blocked by other projects.  For example, I'd like to (at some point) link up amen with [crema](https://github.com/bmcfee/crema) for better pitch class models, as well as root and bass following.  There's no major technical hurdle to doing this, though I do need to do some upgrades to crema to make distribution a bit less painful across platforms.

Similarly, I'd like to add a modernize rhythm model to crema that could be used to power a better beat/downbeat analysis within amen.  I took a stab at this last year, but didn't have time to do a thorough job of this.

Of course, there are also a bunch of less machine-learningy issues to be tackled, mostly around efficiency and use-cases/examples.  If anyone wants to join in and take the initiative on those, I'd be more than happy to help/advise!

**Comment by tkell** [comment]
Hello, ty for the kind words!  

Like Brian said, we've been busy on other things.  I will have time to work on Amen in 2019 - it will be one of my two sideprojects, so some things should happen fairly soon!

**Comment by tomswisher** [comment]
Really appreciate the replies everyone! I can imagine how busy you must be in 2018, so it makes sense this project is taking a breather. My friends and I are thankful for the work you've done for the whole family of audio libraries.

This thread was sparked when I uncovered a short video of my 2014 Pyechonest demo. Maybe it can jog memories of your own projects from back then.
https://www.dropbox.com/s/aeytbikzrwjwvn8/Echoblock_2014.MOV?dl=0
(Recording volume was pretty low. I'm not an Audio Engineer, lol)

**Comment by tkell** [comment]
https://media.giphy.com/media/elnu9VKIfTIzu/giphy.gif

Closing because I am back working on this, hooray!
