### ISSUE TITLE
Creating Audiio Object with Local Wav Files

### ISSUE THREAD

**Issue by ChristinaLyu** [algorithmic-music-exploration/amen#113]
Hi, I want to create a new Audio object with a local wav file, but it's giving me a NoBackendError. I'm wondering if you could please tell me how to fix this. My local wav file is called baiyang.wav. It is located in my local clone of amen, inside the example_audio folder with the two example audio. I used the same command in example_audio_file(). Below is the directory of my file and the error I got. Thank you so much.
<img width="1280" alt="screen shot 2019-02-06 at 4 35 57 pm" src="https://user-images.githubusercontent.com/32347933/52375524-d65fac80-2a2d-11e9-8045-5c354cff733d.png">
<img width="1280" alt="screen shot 2019-02-06 at 4 35 57 pm" src="https://user-images.githubusercontent.com/32347933/52375565-f68f6b80-2a2d-11e9-8bb2-829dc3e3a811.png">

**Comment by ChristinaLyu** [comment]
<img width="1280" alt="screen shot 2019-02-06 at 4 40 48 pm" src="https://user-images.githubusercontent.com/32347933/52375601-0f981c80-2a2e-11e9-9a78-cbba3551d82b.png">

**Comment by tkell** [comment]
Hi there!

That's an error from librosa, a library that Amen uses for reading audio.  You can look around on the internet for various fixes, but [this thread](https://github.com/librosa/librosa/issues/589) is probably a good place to start.

Good luck!
