### ISSUE TITLE
Trouble with librosa

### ISSUE THREAD

**Issue by ChristinaLyu** [algorithmic-music-exploration/amen#114]
I was trying to import amen, but it gave me such error as no module named librosa.
<img width="1280" alt="screen shot 2019-02-11 at 11 36 09 am" src="https://user-images.githubusercontent.com/32347933/52578006-594b8300-2df1-11e9-8ed9-8111f310b894.png">

**Comment by tkell** [comment]
Hmm, so you don't have librosa installed!  You can probably fix this by doing `pip install librosa`.

If that does not work, how did you install amen?

**Comment by tkell** [comment]
Closing due to lack of response - please open a new issue if you are still having problems!
