### ISSUE TITLE
Modernize CI, Python Versions

### ISSUE THREAD

**Issue by tkell** [algorithmic-music-exploration/amen#115]
Hello @bmcfee, nice to see you around this part of the world!

I feel like we should update our CI to work on Python `3.7` and `3.6`, and remove `3.4` and `3.5`.  

I'd also like to add `flake8` and `black` - and then we already have #93 to replace Nose with Pytest.  

Do any of those seem like terrible ideas to you?

- [x] Update CI to use 3.5, 3.6, 3.7
- [x] Fix flake8 issues
- [x] Add flake8 to CI
- [x] Run black
- [x] Add black to CI

**Comment by bmcfee** [comment]
I think we should keep 3.5, but otherwise agree with all that!

**Comment by tkell** [comment]
Closing with #119, #120, #118, #117, and #116  !

🚀 🚀 🚀 🚀 🚀
