### ISSUE TITLE
issue with librosa dependency <<module 'librosa.feature' has no attribute 'rmse'>>

### ISSUE THREAD

**Issue by kingfriday13** [algorithmic-music-exploration/amen#123]
Just an fyi, 

according to the librosa change log for .7.0 >> (Root mean square error (rmse) has been renamed to rms) 

https://github.com/librosa/librosa/blob/17a5852ca1d052cb6f54ca9849c8fd97edf6c939/docs/changelog.rst

**Comment by tkell** [comment]
Yep!  I've got an updated version that I need to release, which should be in a few weeks.  For now, you can drop librosa to 0.6.3.  

Thanks!

**Comment by tkell** [comment]
Fixed in code with #116, fixed in release with #124!
