### ISSUE TITLE
Releasing 0.0.1?

### ISSUE THREAD

**Issue by tkell** [algorithmic-music-exploration/amen#29]
How far out from this are we?  We clearly don't have comparable feature extraction compared to the old remix, but is it worth announcing it / putting it on PyPi anyways?  

Related to this is that the Monthly Music Hackathon for February is Automatic Music, so we could announce it as one of the talks.  

Thoughts?

**Comment by bmcfee** [comment]
I still haven't had a chance to play with it thoroughly yet; i tried last week and got an error with the packaged reversal example.  I'll try dig into it more closely tonight.

Otherwise, I'm all for putting out a preliminary release, if only for feedback and testing.

**Comment by tkell** [comment]
(That error is probably my fault - will take a look this week.)

**Comment by tkell** [comment]
Fix the bug, (https://github.com/algorithmic-music-exploration/amen/pull/31).  

Assuming that there are no more bugs, I feel like we need a nice readme / installation method, and maybe polish the documentation more.  

There's also the issue of the test audio file not giving the correct number of beats back.  Would a longer edit of the Amen break work better?

**Comment by tkell** [comment]
Oh, and will we need to answer the license question before we do a release?

**Comment by tkell** [comment]
Update:  I am wrestling with some vicious RSI, so I am trying to avoid using computers as much as I can.  Thus, I don't think we can get this out for the February hackathon - but we should still try to do it soon!

**Comment by tkell** [comment]
Back on this:

- We have a license, so we're good there.
- I think @bmcfee has worked out most of the egregious bugs.
- I can move my hands again!

Worth making at 0.01?

**Comment by tkell** [comment]
Update:  track/upload closes on May 31st.  I will get this out there before then.

**Comment by tkell** [comment]
Oh, cool, we did this.  Nice work, team.
