### ISSUE TITLE
Analysis object

### ISSUE THREAD

**Issue by bmcfee** [algorithmic-music-exploration/amen#4]
Let's start scoping this thing out!

What functionality does the Analysis object need to provide, and what should the interface look like?

For now, let's not limit ourselves to compatibility with EN remix.  Backwards compatibility can always be tacked on with a translation layer.  I'm more interested in making sure the core is well designed and extensible in the right kinds of ways.

I'll start off a check-list of features it should expose, but the interface can come later.

[EDIT: 2015-06-06, restructured the feature list by type]
- Features (time-indexed)
  - [ ] tempo
  - [ ] key
  - [ ] time signature
  - [ ] timbre (ie MFCC)
  - [ ] pitch class (ie chroma)
  - [ ] pitch (ie cqt)
  - [ ] loudness (log-RMSE)
- Timings
  - [ ] onsets and/or segments/tatums
  - [ ] beat
  - [ ] bar
  - [ ] structural boundaries

Blue-sky feature wish list:
- [ ] instrument activation
- [ ] chord estimations
- [ ] melody/f0 contours
- [ ] high-level rhythmic analysis

Some general design principles:
- all timing measurements should be aligned to the closest zero-crossings, though I'm not sure how to reconcile that with stereo-vs-mono.  Anyone have thoughts on this?
- feature extractors should be modular and pluggable.  I could imagine wanting to refine a particular model's implementation without changing its interface.  Extractors should therefore include semantic versioning in their metadata.  I have a prototype of something like this in [seymour](https://github.com/bmcfee/seymour/blob/master/code/seymour_analyzers/librosa_midlevel.py), but it could be done much better.
- In the interest of minimizing redundancy, it might be good to design so that any feature (pitch, pitch class, timbre, etc) can be sampled relative to any timing (track, beat, onset) with appropriate aggregation (mean, max, median, etc).  I'm not sure what exactly this means for serialization of analysis objects.
- As we've discussed offline, I'm planning to implement a suite of analysis modules that live on top of librosa, but in a separate package.  Probably that package should be a dependency for amen once it stabilizes, since analysis is useful in broader contexts than remix.

**Comment by blacker** [comment]
[documenting offline conversation with @bmcfee ]

The Analysis object will contain
* an Audio object, which will have
  * an audio buffer
  * sample rate
  * # channels
  * duration
  * filename (optional?)
* a Features object, which will have
  * timbre
  * pitch
  * etc etc etc, the point is that this is extensible
* Timing objects: Beats, Bars, Sections, etc. These will probably be pretty stable, i.e. we won't add new ones later, so we don't need to wrap them in a higher-level object the way we do features. 

Each Timing object is basically just a list of TimeSlice objects. A TimeSlice object will have
* start time
* duration
* pointer to an Audio object

You can create an Analysis by passing it a filename, or an Audio object, or an audio buffer. Constructing an Analysis object consists of three steps:
1. Create Audio object
2. Compute Timing objects
3. Compute Features

When serializing an Analysis object, we won't want to include the actual audio buffer, just the filename. Then when deserializing, first we'll reconstruct the Audio object and load the audio, then reconstruct the TimeSlice objects and point them at the Audio object.

**Comment by tkell** [comment]
I want to close this monster and make separate issues for each Feature and Timing that we need.  Shout if that is a bad idea.

**Comment by tkell** [comment]
Closing as it was our original spec.  Will make an issue for making more issues!
