### ISSUE TITLE
Feature:  Timbre

### ISSUE THREAD

**Issue by tkell** [algorithmic-music-exploration/amen#44]
Librosa gives us MFCCs - we should use those.

**Comment by tkell** [comment]
This also needs to go into the Echo Nest Converter.

**Comment by tkell** [comment]
Paging @bmcfee:  We can get, say, 20 MFCCS really easily - but do they then go in a FeatureCollection like so:

```
{
  0: 0.45,
  1: 0.5654,
  2: 1.234,
}
(etc)
```

Numeric keys to dicts feel odd to me- do we have another way of doing it?  I don't think so, at first blush.

**Comment by tkell** [comment]
Took a shot in #81, regardless.

**Comment by Cortexelus** [comment]
I asked Tristan Jehan and this is how he computed timbre on segments:

- PCA
- on spectrograms (23 critical bands at a sampling rate of 22050 Hz)
- using a large set of segments from different genres

For segments, he preserved the onset transient and normalized the length: 
> To normalize the length, yes, I preserve the transient (that is 10 frames or ~58 ms, i.e. 128 samples per frame x 10 frames at 22050 Hz), then resample the remainder to 10 frames. That's a total of 23 x 20 = 460 dimensions. That gets condensed to 12 via PCA, or rather 11 as the 1st dimension is forced to the average.

**Comment by Cortexelus** [comment]
You can assign this to me. I have a large dataset of creative commons music in a wide variety of styles. I have a Telsa K80. I'll use incremental PCA to process segments in batches. I'll find the 12 basis functions.

**Comment by tkell** [comment]
Hello @Cortexelus!  I don't think we need to exactly replicate Echo Nest timbre - and remember that we need to make sure whatever we get works at the frame level, so that it scales like everything else.

With that said, please take a shot at it!  If we can make it make sense with the rest of the system, it'd be rad to have

**Comment by Cortexelus** [comment]
Ah! The timbre I'm on about works at the segment level (subdivisions according to onsets).

**Comment by tkell** [comment]
Yeah, we don't have Echo Nest segments in this, and I don't want to have a Feature that does not work like all the other ones.  Surely this would work on frames as well?

**Comment by Cortexelus** [comment]
Echo Nest segments were my favorite part of remix. They're essential. I already implemented a variation of Tristan's segmenter. He describes it in a few of his Media Lab papers. I can contribute that too.

**Comment by Cortexelus** [comment]
MFCCs do a great job on frames already. But cool thing about segment timbre is that it's spectro-temporal envelope info.

**Comment by Cortexelus** [comment]
I could also do MFCCs over time. Cepstral-temporal. I wonder how to best evaluate timbre representations. 

Either way, the result of PCA on a dataset of music is a projection matrix which turns any arbitrary segment into a low-dimensional vector. Then it's more tractable to do stuff like similarity matrices, sorting, clustering.

**Comment by tkell** [comment]
So the the thing to do is to build segments as some sort of Timing (https://github.com/algorithmic-music-exploration/amen/blob/master/amen/timing.py), and then we can get any Feature we want at the segment level.

**Comment by tkell** [comment]
Closed with #81.  CJ, I am going to create a new issue for Echo Nest segments.
