### ISSUE TITLE
Feature:  Pitch Class

### ISSUE THREAD

**Issue by tkell** [algorithmic-music-exploration/amen#45]
Started in #40.  I think the only open question is what we should name the keys in the FeatureCollection.

**Comment by wxy656** [comment]
can keys named as ['A', 'A#', 'B', 'C', 'C#', 'D', 'D#', 'E', 'F', 'F#', 'G', 'G#' ]?

**Comment by tkell** [comment]
Oh, cool, we did this with #40.
