### ISSUE TITLE
Feature:  Onsets

### ISSUE THREAD

**Issue by tkell** [algorithmic-music-exploration/amen#48]
I suspect we can get this with `librosa.onset.onset_detect`

**Comment by Cortexelus** [comment]
Onsets make good segments, but the onset times themselves are not the best boundaries. 

1. We want to find the nearest zero-crossing
 - less likely to get clicks when you concatenate
2. We want to set the segment boundary earlier to include the pre-onset head/attack. 
 - less likely to hear next segment in the tail of the first
 - locate by backtracking to point of lower spectral flux
 - observe the various ways (from this [IRCAM MuBu paper](http://articles.ircam.fr/textes/Schnell09a/index.pdf)) 
![image](https://cloud.githubusercontent.com/assets/2453861/18576270/01c63302-7bae-11e6-846e-ac3edc8ce059.png)

3. We may also want to include 
 - time of max amplitude (originally in the echonest api)
 - good points to ping-pong loop this segment's samples for an Ableton-style time stretch. Perhaps a period of low spectral flux at least 100ms.


This is my aesthetic opinion from building concatenative synths and playing with librosa's onset_detection

**Comment by bmcfee** [comment]
@Cortexelus fair points. Have you seen the onset tweaking thread in the librosa issues?

**Comment by Cortexelus** [comment]
Yeah. A simple backtracking method like the one @kylemcdonald explains is what I was thinking. (But now this time reassignment stuff is new to me and I am exploring it.)

**Comment by Cortexelus** [comment]
It's useful to include both an onset time and a starting boundary. For example, in a rhythmic concat synth, you may want to start the segment early (pre-onset head) but align its onset time to the beat/pattern grid. This way a lengthy head doesn't interfere with the pulse of the pattern, but you still hear the full head (overlapped with the previous segments' tail)

**Comment by Cortexelus** [comment]
I summon Tristan Jehan's thesis.

![image](https://cloud.githubusercontent.com/assets/2453861/18606055/cd0c68ec-7c71-11e6-818b-8f371e7e1ae2.png)
![image](https://cloud.githubusercontent.com/assets/2453861/18606059/ea87841a-7c71-11e6-9cc1-70159478fdfd.png)

**Comment by tkell** [comment]
Closed with #95 !
