### ISSUE TITLE
Feature object

### ISSUE THREAD

**Issue by bmcfee** [algorithmic-music-exploration/amen#6]
Starting a new thread to expand on the feature object design that I vaguely started in #4.

In the previous jam, we had features like 'timbre' and 'pitch' connected to segments.  I'd like to abstract out features from timing in amen, since different features may come at different sampling rates.  Here, I'm distinguishing feature observations like 'pitch' and 'timbre' from time-index observations, like 'beat' and 'segment'.

To make this all work, I'm thinking of the following design.  First, features are stored as pandas dataframes with a time-valued index.  This gives us a few nice features right off the bat:

* direct connection between a feature observation and its position in the audio signal
* sane column-headings, eg, `pitch['D#']` instead of `pitch[4]`
* numpy-friendly operations (slicing, math)
* sql-like operations (joining, merging)
* time-friendly resampling

Then, we can define a `Feature` class which wraps the dataframe, and provides a few extra operations:
* re-indexing, relative to a `TimeSlice` collection.  This way, we can index a feature object (say, `pitch_class`) by any type of time-interval indices (eg, 'beats' or 'segments')
* data-dependent interpolation logic.  Re-indexing will necessarily involve some statistical summarization if the time points span multiple values.  Numeric types may be summarized by different statistics (mean, median, max); categorical types (eg, chord labels) may be summarized by mode.  This definition will be part of the corresponding derived Feature class
* iteration over observations (rows) of the dataframe

At the end of the day, the old style of
```python
>>> [beat.pitches for beat in track.beats]
```
would look more like
```python
>>> track.features.pitch[beats]
```
with the added benefit that indexing the `Feature` object `pitch` will return a new `Feature` object (with time indexing and column headers), rather than a flat list.

**Comment by bmcfee** [comment]
Does it make sense to have something like a `FeatureCollection` object that groups individual features (eg, pitches and timbres)?

I'm imagining a use case where you want, say, pitches and timbres, sampled per beat.  Indexing each feature individually would be a bit of a pain:

```python
>>> for (timbre, pitch) in zip(track.features.timbre[beats], track.features.pitch[beats]):
    ...
```

Instead, if we could make the feature collection support time indexing:
```python
>>> for beat_features in track.features.at(track.beats):
    timbre = beat_features['timbre']
    pitch = beat_features['pitch']
    ...
```

A FeatureCollection could again be backed by a pandas dataframe, but now using a hierarchical column index.  (I imagine this would be constructed on the fly, to keep the memory consumption down.)

**Comment by bmcfee** [comment]
Another thought: it might be useful to allow the user to override the default resample/aggregation function.

For instance, most numerical features probably should use mean aggregation for downsampling against, say, beats, but the user might have something different in mind, eg, variance or ohlc might be sometimes useful.

**Comment by blacker** [comment]
I agree that it's useful to be able to neatly access multiple features for a given `TimeSlice`, although the `FeatureCollection` approach requires the user to go fetch the actual `TimeSlice` separately:

```python
>>> def my_generator(Track):
    cur = 0
    i, beat_features in enumerate(track.features[track.beats]):
        if beat_features.timbre[3] > 0.1 and beat_features.pitch['d'] > 0.3:
            yield cur, track.beats[i]
            cur += track.beats[i].duration
```

Would it make more sense to be able to index an individual feature by a specific `TimeSlice`? Like

```python
>>> def my_generator(Track):
    cur = 0
    for beat in track.beats:
        if track.features.timbre[beat][3] > 0.1 and beat.features.pitch[beat]['d'] > 0.3:
            yield cur, beat
            cur += beat.duration

**Comment by blacker** [comment]
and +1 for allowing user's to implement custom resample/aggregation logic for a feature

**Comment by bmcfee** [comment]
> Would it make more sense to be able to index an individual feature by a specific TimeSlice?

I suppose it all depends on how we want to define the slicing operation.

In the first example, ``track.features`` is indexed by an array of ``TimeSlice`` objects, and presumably returns a new ``FeatureCollection`` (after aggregation) which is then iterated row-wise.

The the second example, each ``FeatureCollection`` is indexed by a single ``TimeSlice`` and returns a row of the (aggregated) feature collection.

I suppose we could support both, but I'm not sure at the moment which is more natural.  The first example seems slightly more consistent to me, when it comes down to indexing the aggregated feature data, since you're always indexing a ``Feature`` by column headers (and not time).  However, it might end up looking more like:
```python
beat_features['timbre', 3] > 0.1 and beat_features['pitch', 'D'] > 0.3
```
depending on how much smarts we want to embed into the slice object when interacting with pandas.

Anyone else have preferences on this?

**Comment by tkell** [comment]
+1 to this.  I think our talk at MMHD June ended up with:

`some_feature_collection['pitches'].at(some_time_slice_collection)`

**Comment by bmcfee** [comment]
alternatively:
```python
beat_features = feature_collection.at(beats)
beat_features['pitch']
```

**Comment by blacker** [comment]
Is this a case where we should settle on just one way to do it? I prefer the second way, because it makes it easier to do
```python
for beat in feature_collection.at(beats):
    beat['pitch']
    beat['timbre']
```

**Comment by tkell** [comment]
I think we get both, do we not?  .at will work on a FeatureCollection, regardless of what is in it.

**Comment by bmcfee** [comment]
> since you're always indexing a Feature by column headers (and not time).

Talking with @tkell today: I think we're ok with indexing by either a TimeSlice or a collection of TimeSlices.

**Comment by tkell** [comment]
This is in a decent place, in feature.py - I need to write a few more tests and then we'll have it.

**Comment by tkell** [comment]
I think we can close this - we need to add more features, but the basic stuff is here.
