### ISSUE TITLE
Loading Audio

### ISSUE THREAD

**Issue by tkell** [algorithmic-music-exploration/amen#7]
..brought to you by a frustrating day reinstalling my Ubuntu partition.  

For the moment, I think we just worry about loading WAV and MP3 - Brian's said that librosa can deal with both of them.  

I feel like we want to do `analysis = amen.load('some_audio_file.wav')`.  Does this generate all analyses that are possible?  Or do we do something like: 

```
audio = amen.load('some_audio_file')
audio.get_analysis('pitches')
audio.get_time_slices('beats') # this needs a better name
audio['pitches'].at(audio.beats)
# do something with beats and pitch analysis

```

The former has the advantage of being simple - even people who don't know what they're looking for can get analysis data with a single line of code.  The latter has the advantage of being faster, more modular, and more specific.  

Or, maybe we generate some basic things when we do `amen.load` (beats, pitches, etc?) - but if you want, say, some black-magic timbre analysis, you can run `audio.get_analysis('black_magic_timbre')

**Comment by blacker** [comment]
I never want to have to tell amen what it needs to analyze. I think it should figure it out on its own and do it as lazily as possible. So you just do ``analysis = amen.load('whatever.mp3')`` and the first time you ask for ``analysis['pitches'].at(analysis.beats)`` it does those analyses.

**Comment by bmcfee** [comment]
> I think it should figure it out on its own and do it as lazily as possible.

Once the audio's decoded and in memory, most of the analysis should be fast (ie, near linear time).  I think it would be simplest all around to just have `amen.load` call out to a big beefy analysis routine that constructs all the feature and timing objects up front.

**Comment by tkell** [comment]
Got it.  So to combine these, we make `amen.load` do a whole set of basic analyses, but when we call `analysis['crazy_expensive_timbre_analysis']`, it goes out and gets that crazy analysis.  Sound OK?

**Comment by bmcfee** [comment]
Sure.

More generally, we've been planning to have a core set of `Feature` implementations that can change and/or grow later on in subsequent versions.  Does it also make sense to generally make this dynamic? 

For instance, say I write an analyzer that can find all the cowbells in a song.  We could probably just add a new `Feature` object to the `FeatureCollection` as needed, if it acts as a dict-like, and then have it go on its merry way.

**Comment by tkell** [comment]
I approve!

**Comment by tkell** [comment]
Also thing that we've got this - re-open if you disagree.
