### ISSUE TITLE
Don't snipe http://readme.md

### ISSUE THREAD

**Issue by MegaApuTurkUltra** [algorithmic-music-exploration/amen#77]
You guys are preventing it from being used for something more interesting :smile:

**Comment by bmcfee** [comment]
I don't understand your post. Clarify please?

**Comment by tkell** [comment]
Ahhh, I understand.

@bmcfee, Brian Whitman owns www.readme.md.  It used to route to pyechonest, then remix, and now it routes here.  

@MegaApuTurkUltra, the owner of readme.md is not part of this organization.  I'll drop him a line, but I suspect that he won't change anything.

**Comment by TalenceCrouch** [comment]
Hi what is your project can I help?
