### ISSUE TITLE
Potential processing using sox.py

### ISSUE THREAD

**Issue by tkell** [algorithmic-music-exploration/amen#80]
https://github.com/marl/medleydb/blob/master/medleydb/sox.py

^^ Are there things we can do with this?  Or does the fact that sox mostly works on files, not np.arrays make it not worth it.

**Comment by bmcfee** [comment]
I think it's not worth it for core amen stuff, for two reasons:

1. it requires serialization / deserialization of audio data to work (like you say),
2. it adds a dependency to sox, which makes package maintenance much more difficult.

OTOH, if you wanted to write effects chains on top of amen using [pysox](https://github.com/rabitt/pysox), that wouldn't be difficult.

**Comment by tkell** [comment]
Hm.  Yeah, I want to avoid making people have sox, but I'd also rather not eventually reimplement a filter.

Closing for now, maybe we'll wrestle with it later.
