### ISSUE TITLE
Porting from Echonest

### ISSUE THREAD

**Issue by MikeiLL** [algorithmic-music-exploration/amen#85]
Thank you! We're porting a web app from Echonest that is basically a fork of P. Sobot's [Forever.fm](https://github.com/psobot/foreverfm) and a couple of features we require are:

   1.  Crossfade (which was coming from Action/[cAction](https://github.com/echonest/remix/blob/ca227c9d885689e2fc8cad02171d2c29a167fa73/external/cAction/actionmodule.cpp))
    2.  AudioData (which I [grabbed](https://github.com/echonest/remix/blob/master/src/echonest/remix/audio.py along with the [ffmpeg wrapper](https://github.com/echonest/remix/blob/master/src/echonest/remix/support/ffmpeg.py) it depended on)

We were using a few other Capsule functions as well and I'm wondering if there are any plans to incorporate any of these remix helpers into Amen.

If it does make sense to include AudioData (and even AudioStream) I can add them to my fork and submit a PR.

**Comment by tkell** [comment]
Hello!

We don't intend to recreate objects from Remix.  We are working on a tool for producing JSON that Remix can read, which is at `echo_nest_converter.py`.

We _may_ add things like crossfading, but they're a long way off.  We don't plan to support ffmpeg.

Without knowing much about the details of your app, I'd venture that your best bet is to use the above `echo_nest_converter.py` to produce JSON that Remix can read, and then keep the rest of your app the same.

Good luck!

**Comment by MikeiLL** [comment]
OK. Thanks for clarifying, Thor. Are you saying that basically we can continue to use Remix, but replace calls to the EchoNest API with the `echo_nest_converter.AudioAnalysis` object?

**Comment by tkell** [comment]
Hello!

That should work, yes - though we don't match all features of Remix exactly.  

Alternatively, you can use `echo_nest_converter.py` to produce a JSON file that Remix can read.
