### ISSUE TITLE
version 0.0.0

### ISSUE THREAD

**Issue by stevenalanstark** [algorithmic-music-exploration/amen#86]
pip install is failing to find new lib changes because there are no version changes, the version is always 0.0.0.

In order to install, I can not use `pip install amen`, I need to instead use `pip install git+git://github.com/algorithmic-music-exploration/amen`

**Comment by tkell** [comment]
You mean that installing from pip always gets you the version at https://pypi.python.org/pypi/amen/0.0.0, rather than the latest code?

**Comment by stevenalanstark** [comment]
yes, correct. Both methods of installing result in version `0.0.0`, but have different code. For example, it's missing the echonest files. 

I see in the code the version is set to `0.0.0` here: https://github.com/algorithmic-music-exploration/amen/blob/master/amen/version.py#L6

**Comment by tkell** [comment]
Got it – we have not done a formal release in while, is all.  I'm wrestling with some other code, but once I am back to this, I will make 0.0.1.

I'm going to close this issue and make a new one for making a new release.  Thanks for the reminder!

**Comment by tkell** [comment]
Done!
