### ISSUE TITLE
Features via vamp

### ISSUE THREAD

**Issue by bmcfee** [algorithmic-music-exploration/amen#9]
This package is awesome: https://pypi.python.org/pypi/vamp

I think it would be pretty easy to build some glue that converts vamp outputs into feature objects ala #6 .

**Comment by blacker** [comment]
Wow yeah, vamp is awesome.

So this glue would let people use *any* vamp plugin as the basis for algoremixing?

**Comment by tkell** [comment]
a)  I think this is feature-creepy, a little
b)  I think if we build things right, we can do this really easily, which would be super nice.

**Comment by bmcfee** [comment]
@tkell agreed.  My thinking though, is that providing a small amount of vamp glue would let people plug in things like melodia to get melody contours, without us having to rewrite everything from scratch.  Since we're not imposing any particular timing grid on the feature objects, this should be seamless and easy to do.
